# Generated by Django 3.2.12 on 2022-06-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0010_pointofservice_pricingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='point_of_services',
        ),
        migrations.DeleteModel(
            name='Pointofservice',
        ),
        migrations.DeleteModel(
            name='Pricingplan',
        ),
    ]
