# Generated by Django 3.2.12 on 2022-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0012_pointofservice_pricingplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pointofservice',
        ),
        migrations.DeleteModel(
            name='Pricingplan',
        ),
    ]
