# Generated by Django 3.2.12 on 2022-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0016_pointofservice_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membershipcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=150)),
                ('service_name', models.CharField(max_length=150)),
                ('customer_id', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=150)),
                ('customer_number', models.CharField(max_length=150)),
                ('customer_message', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Membership Customer',
                'verbose_name_plural': 'Membership Customer',
            },
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
