# Generated by Django 3.2.12 on 2022-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0018_auto_20220701_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
