# Generated by Django 3.2.12 on 2022-06-04 09:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_doctorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='jgjgjgjg', editable=False, populate_from='doctor_name'),
            preserve_default=False,
        ),
    ]
