# Generated by Django 3.2.12 on 2022-06-04 09:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_doctorprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='doctor_name', unique=True),
        ),
    ]
